chore: freshen Gemfile.lock
    brew install chruby
    brew install ruby-install
    ruby-install --latest ruby
    source /usr/local/opt/chruby/share/chruby/chruby.sh
    chruby 3.1.3
    rm Gemfile.lock
    bundle

To see if that fixes new CI failures caused by changes in GitHub Actions
as seen here:

- https://github.com/wincent/command-t/actions/runs/3689296487/jobs/6245086655

    Bundler 2.3.5 is running, but your lockfile was generated with 2.0.2. Installing Bundler 2.0.2 and restarting using that version.

    ...

    Using bundler 2.0.2
    Following files may not be writable, so sudo is needed:
      /var/lib/gems/3.0.0
      /var/lib/gems/3.0.0/build_info
      /var/lib/gems/3.0.0/cache
      /var/lib/gems/3.0.0/doc
      /var/lib/gems/3.0.0/extensions
      /var/lib/gems/3.0.0/gems
      /var/lib/gems/3.0.0/plugins
      /var/lib/gems/3.0.0/specifications
    Fetching diff-lcs 1.3
    /var/lib/gems/3.0.0/gems/bundler-2.0.2/lib/bundler/shared_helpers.rb:36: warning: Pathname#untaint is deprecated and will be removed in Ruby 3.2.
    ArgumentError: wrong number of arguments (given 2, expected 1)
    An error occurred while installing diff-lcs (1.3), and Bundler cannot continue.
    Make sure that `gem install diff-lcs -v '1.3' --source 'https://rubygems.org/'`
    succeeds before bundling.

    In Gemfile:
      rspec was resolved to 3.9.0, which depends on
        rspec-expectations was resolved to 3.9.0, which depends on
          diff-lcs